name: deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: swatinem/rust-cache@v2
      - run: ./scripts/check.sh

  deploy:
    needs: check
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Rust Setup
        uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - run: rustup target add wasm32-unknown-unknown
      - name: Install trunk (prebuilt binary)
        uses: jetli/trunk-action@v0.5.1
        with:
          version: "v0.21.14"
      - name: Build
        run: trunk build --release --public-url khanatime
        working-directory: ./
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4