name: test
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: cargo test

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: swatinem/rust-cache@v2
      - run: cargo clippy --all-targets -- -D warnings
